name: CD Deploy React Portfolio to EC2

on:
  workflow_dispatch:   # manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name:  Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            echo "Docker login"
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            echo "Pull latest image"
            docker pull ${{ secrets.DOCKER_USERNAME }}/react-portfolio:latest

            echo "Stop old container"
            docker stop react-portfolio || true

            echo "Remove old container"
            docker rm react-portfolio || true

            echo "Run new container"
            docker run -d -p 80:80 --name react-portfolio ${{ secrets.DOCKER_USERNAME }}/react-portfolio:latest

            echo "Deployment done"
