name: CD Deploy React Portfolio to EC2

on:
  workflow_dispatch:
    inputs:
      image:
        description: "Image name from CI"
        required: true
      tag:
        description: "Image tag from CI"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |

            echo "===== CD START ====="

            IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.image }}:${{ github.event.inputs.tag }}
            CONTAINER=react-portfolio

            echo "Image: $IMAGE"
            echo "Container: $CONTAINER"

            echo "Docker version:"
            docker --version

            echo "Logging into DockerHub..."
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            echo "Pulling image..."
            docker pull $IMAGE

            echo "Stopping old container if exists..."
            docker stop $CONTAINER || true
            docker rm $CONTAINER || true

            echo "Running new container..."
            docker run -d -p 80:80 --name $CONTAINER $IMAGE

            echo "Containers running now:"
            docker ps -a

            echo "===== CD END ====="
