name: tech-portfolio-ci

on:
  push:
    branches:
      - main
      - develop-*

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.vars.outputs.image }}
      tag: ${{ steps.vars.outputs.tag }}

    steps:
      - uses: actions/checkout@v3

      # read version.txt
      - name: Read version file
        id: vars
        run: |
          IMAGE_NAME=$(grep '^image_name=' version.txt | cut -d '=' -f2 | tr -d ' \r')
          VERSION=$(grep '^version=' version.txt | cut -d '=' -f2 | tr -d ' \r')
          BUILD=${{ github.run_number }}
          FINAL_TAG=$VERSION.$BUILD

          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "tag=$FINAL_TAG" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

      - uses: docker/setup-buildx-action@v3

      # login only main
      - name: Login DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # build
      - name: Build Docker
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ steps.vars.outputs.image }}
          TAG=${{ steps.vars.outputs.tag }}

          docker buildx build . \
            --platform linux/amd64 \
            --tag $IMAGE:$TAG \
            --tag $IMAGE:latest \
            --load

      # push only main
      - name: Push Docker
        if: github.ref == 'refs/heads/main'
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ steps.vars.outputs.image }}
          TAG=${{ steps.vars.outputs.tag }}

          docker push $IMAGE:$TAG
          docker push $IMAGE:latest

      # ðŸ”¥ TRIGGER CD AFTER SUCCESS
      - name: Trigger CD
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/workflow-dispatch@v2
        with:
          workflow: cd.yml
          inputs:
            image: ${{ steps.vars.outputs.image }}
            tag: ${{ steps.vars.outputs.tag }}

