name: tech-portfolio-ci

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.vars.outputs.image }}
      tag: ${{ steps.vars.outputs.tag }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ðŸ”¹ Read version.txt
      - name: Read version file
        id: vars
        run: |
          IMAGE_NAME=$(grep image_name version.txt | cut -d '=' -f2)
          VERSION=$(grep version version.txt | cut -d '=' -f2)
          BUILD=${{ github.run_number }}

          FINAL_TAG=$VERSION.$BUILD

          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "tag=$FINAL_TAG" >> $GITHUB_OUTPUT

          echo "IMAGE_NAME=$IMAGE_NAME"
          echo "FINAL_TAG=$FINAL_TAG"

      # ðŸ”¹ Node setup
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      # ðŸ”¹ Docker setup
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ðŸ”¹ Build & Push image
      - name: Build and Push Docker Image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ steps.vars.outputs.image }}
          TAG=${{ steps.vars.outputs.tag }}

          echo "Building $IMAGE:$TAG"

          docker buildx build . \
            --platform linux/amd64 \
            --tag $IMAGE:$TAG \
            --tag $IMAGE:latest \
            --push
